name: Han50l0
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1776506919413805
title: Han50L0 - Surfing the web on one social swell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe4e7'
    - '#b0b8bb'
    - '#ad8e7c'
    - '#373332'
    - '#171312'
  brandStrength: 0.25
  lightness: 0.5981400061864406
  saturation: 0.6875
  rhythmicContrast: 0.47972783306613564
purpose: []
